server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/yourdatabase
    username: projectuser
    password: projectpassword
    driver-class-name: org.postgresql.Driver
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/yourdatabase
    username: projectuser
    password: projectpassword
  sql:
    init:
      mode: always  # Runs schema.sql on startup to initialize the database
  jpa:
    hibernate:
      ddl-auto: none  # Ensures the schema.sql is used instead of Hibernate's automatic schema generation
  logging:
    level:
      root: INFO
      com.example: DEBUG  # Set this according to your package structure

# Configures initialization scripts
spring.sql.init.schema-locations: classpath:sql/schema.sql
spring.sql.init.data-locations: classpath:sql/data.sql  # Optional: populate with initial data
